# Generated by Django 5.2.6 on 2025-09-30 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('service', models.CharField(choices=[('Laundry', 'Laundry'), ('Dry Cleaning', 'Dry Cleaning'), ('Ironing', 'Ironing'), ('Other', 'Other')], max_length=32)),
                ('address', models.TextField()),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
