# Generated by Django 5.2.6 on 2025-09-30 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('garments', models.IntegerField()),
                ('turnaround', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('features', models.TextField(help_text='One feature per line')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='RateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('household', 'Household'), ('footwear', 'Footwear')], max_length=32)),
                ('item', models.CharField(max_length=255)),
                ('washFold', models.IntegerField(blank=True, null=True)),
                ('dryClean', models.IntegerField(blank=True, null=True)),
                ('iron', models.IntegerField(blank=True, null=True)),
                ('steamIron', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['category', 'item'],
            },
        ),
    ]
