# Generated by Django 5.2.6 on 2025-09-30 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_packageplan_rateitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_number', models.CharField(help_text='WhatsApp user phone', max_length=32)),
                ('wa_name', models.CharField(blank=True, max_length=255)),
                ('message_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='received', max_length=16)),
                ('raw_payload', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
