services:
  - type: web
    name: foldfresh-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn foldfresh_django.wsgi:application
    envVars:
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_ALLOWED_HOSTS
        value: "foldfresh.in,www.foldfresh.in,your-backend-url.onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://foldfresh.in,https://www.foldfresh.in,https://your-frontend-url.vercel.app"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://foldfresh.in,https://www.foldfresh.in,https://your-frontend-url.vercel.app"
      - key: SECURE_SSL_REDIRECT
        value: "True"
      - key: SESSION_COOKIE_SECURE
        value: "True"
      - key: CSRF_COOKIE_SECURE
        value: "True"
      - key: SECURE_HSTS_SECONDS
        value: "31536000"
      - key: SECURE_HSTS_INCLUDE_SUBDOMAINS
        value: "True"
      - key: SECURE_HSTS_PRELOAD
        value: "True"
      - key: SECURE_REFERRER_POLICY
        value: "same-origin"
      - key: WHATSAPP_NUMBER
        value: "919999999999"
      - key: PHONE_DISPLAY
        value: "+91 98765 43210"
      - key: PHONE_NUMBER
        value: "919876543210"
      - key: INSTAGRAM_HANDLE
        value: "foldfresh.in"
      - key: COMPANY_NAME
        value: "Foldfresh"
      - key: WHATSAPP_VERIFY_TOKEN
        generateValue: true
      - key: THROTTLE_ANON
        value: "60/min"
      - key: THROTTLE_USER
        value: "120/min"
